-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-04-25 00:50:57 MYT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo on
SPOOL cruiseitineraries_schema_output.txt

--student id: 33520054
--student name: Ang Qiao Xin
DROP TABLE ADDRESS CASCADE CONSTRAINTS 
;

DROP TABLE CABIN CASCADE CONSTRAINTS 
;

DROP TABLE COUNTRY CASCADE CONSTRAINTS 
;

DROP TABLE CRUISE CASCADE CONSTRAINTS 
;

DROP TABLE GENDER CASCADE CONSTRAINTS 
;

DROP TABLE ITINERARY CASCADE CONSTRAINTS 
;

DROP TABLE MANIFEST CASCADE CONSTRAINTS 
;

DROP TABLE OPERATOR CASCADE CONSTRAINTS 
;

DROP TABLE PASSENGER CASCADE CONSTRAINTS 
;

DROP TABLE PORT CASCADE CONSTRAINTS 
;

DROP TABLE SHIP CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ADDRESS 
    ( 
     add_id        NUMBER (7)  NOT NULL , 
     add_street_no VARCHAR2 (50)  NOT NULL , 
     add_town      VARCHAR2 (100)  NOT NULL , 
     add_postcode  VARCHAR2 (10)  NOT NULL , 
     add_country   VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN ADDRESS.add_id IS 'Address identifier (surrogate key)' 
;

COMMENT ON COLUMN ADDRESS.add_street_no IS 'Street number of address' 
;

COMMENT ON COLUMN ADDRESS.add_town IS 'Town of address' 
;

COMMENT ON COLUMN ADDRESS.add_postcode IS 'Postcode of address' 
;

COMMENT ON COLUMN ADDRESS.add_country IS 'Country of address' 
;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_PK PRIMARY KEY ( add_id ) ;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_UQ UNIQUE ( add_street_no , add_town , add_postcode , add_country ) ;

CREATE TABLE CABIN 
    ( 
     cabin_no             VARCHAR2 (7)  NOT NULL , 
     ship_code            NUMBER (7)  NOT NULL , 
     cabin_sleep_capacity NUMBER (5)  NOT NULL , 
     cabin_class          CHAR (1)  NOT NULL 
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT chk_cabinclass 
    CHECK (cabin_class IN ('B', 'I', 'O', 'S')) 
;

COMMENT ON COLUMN CABIN.cabin_no IS 'Cabin unique number identifier' 
;

COMMENT ON COLUMN CABIN.ship_code IS 'Ship identifier' 
;

COMMENT ON COLUMN CABIN.cabin_sleep_capacity IS 'Cabin''s sleeping capacity' 
;

COMMENT ON COLUMN CABIN.cabin_class IS 'Cabin''s class (I -Interior, O- Ocean view , B-Balcony, S- Suite)' 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT CABIN_PK PRIMARY KEY ( cabin_no, ship_code ) ;

CREATE TABLE COUNTRY 
    ( 
     country_code CHAR (3)  NOT NULL , 
     country_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN COUNTRY.country_code IS 'Country code act as identifier' 
;

COMMENT ON COLUMN COUNTRY.country_name IS 'Name of the country' 
;

ALTER TABLE COUNTRY 
    ADD CONSTRAINT COUNTRY_PK PRIMARY KEY ( country_code ) ;

CREATE TABLE CRUISE 
    ( 
     cruise_id              NUMBER (4)  NOT NULL , 
     cruise_name            VARCHAR2 (50)  NOT NULL , 
     cruise_desc            VARCHAR2 (100)  NOT NULL , 
     cruise_depart_datetime DATE  NOT NULL , 
     cruise_cost            NUMBER (15,2)  NOT NULL , 
     ship_code              NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CRUISE.cruise_id IS 'Cruise identifier' 
;

COMMENT ON COLUMN CRUISE.cruise_name IS 'Name of cruise' 
;

COMMENT ON COLUMN CRUISE.cruise_desc IS 'Brief cruise description' 
;

COMMENT ON COLUMN CRUISE.cruise_depart_datetime IS 'The depart date and time of cruise' 
;

COMMENT ON COLUMN CRUISE.cruise_cost IS 'Cost of cruise' 
;

COMMENT ON COLUMN CRUISE.ship_code IS 'Ship identifier' 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT CRUISE_PK PRIMARY KEY ( cruise_id ) ;

CREATE TABLE GENDER 
    ( 
     gender_id   CHAR (1)  NOT NULL , 
     gender_desc VARCHAR2 (20)  NOT NULL 
    ) 
;

ALTER TABLE GENDER 
    ADD CONSTRAINT chk_genderid 
    CHECK (gender_id IN ('F', 'M', 'N', 'O', 'T')) 
;

COMMENT ON COLUMN GENDER.gender_id IS 'Gender identifier (F-Female, M-Male, N-Non-Binary, T-Transgender, O-Others)' 
;

COMMENT ON COLUMN GENDER.gender_desc IS 'Gender id''s description (F-Female, M-Male, N-Non-Binary, T-Transgender, O-Others)' 
;

ALTER TABLE GENDER 
    ADD CONSTRAINT GENDER_PK PRIMARY KEY ( gender_id ) ;

CREATE TABLE ITINERARY 
    ( 
     cruise_id           NUMBER (4)  NOT NULL , 
     iti_depart_datetime DATE  NOT NULL , 
     iti_depart_type     CHAR (1)  NOT NULL , 
     port_code           CHAR (5)  NOT NULL 
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT chk_itinerarydepart_type 
    CHECK (iti_depart_type IN ('A', 'D')) 
;

COMMENT ON COLUMN ITINERARY.cruise_id IS 'Cruise identifier' 
;

COMMENT ON COLUMN ITINERARY.iti_depart_datetime IS 'Date time of depart or arrival' 
;

COMMENT ON COLUMN ITINERARY.iti_depart_type IS 'Itinerary depart or arrive (A- Arrive, D-Depart)' 
;

COMMENT ON COLUMN ITINERARY.port_code IS 'Port code identifier' 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT ITINERARY_PK PRIMARY KEY ( cruise_id, iti_depart_datetime ) ;

CREATE TABLE MANIFEST 
    ( 
     cruise_id      NUMBER (4)  NOT NULL , 
     pass_id        NUMBER (7)  NOT NULL , 
     board_datetime DATE  NOT NULL , 
     cabin_no       VARCHAR2 (7)  NOT NULL , 
     ship_code      NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN MANIFEST.cruise_id IS 'Cruise identifier' 
;

COMMENT ON COLUMN MANIFEST.pass_id IS 'Passenger identifier
Foreign key to another passenger acting as a guardian (only applicable for minors and named guardian_id)' 
;

COMMENT ON COLUMN MANIFEST.board_datetime IS 'Date time when passenger first board the ship' 
;

COMMENT ON COLUMN MANIFEST.cabin_no IS 'Cabin unique number identifier' 
;

COMMENT ON COLUMN MANIFEST.ship_code IS 'Ship identifier' 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT MANIFEST_PK PRIMARY KEY ( cruise_id, pass_id ) ;

CREATE TABLE OPERATOR 
    ( 
     oper_id       NUMBER (7)  NOT NULL , 
     oper_name     VARCHAR2 (50)  NOT NULL , 
     oper_ceo_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN OPERATOR.oper_id IS 'Operator ID identifier' 
;

COMMENT ON COLUMN OPERATOR.oper_name IS 'Operator''s name' 
;

COMMENT ON COLUMN OPERATOR.oper_ceo_name IS 'Name of ceo of operator' 
;

ALTER TABLE OPERATOR 
    ADD CONSTRAINT OPERATOR_PK PRIMARY KEY ( oper_id ) ;

CREATE TABLE PASSENGER 
    ( 
     pass_id     NUMBER (7)  NOT NULL , 
     pass_fname  VARCHAR2 (50)  NOT NULL , 
     pass_lname  VARCHAR2 (50)  NOT NULL , 
     pass_dob    DATE  NOT NULL , 
     pass_phone  VARCHAR2 (20) , 
     guardian_id NUMBER (7) , 
     add_id      NUMBER (7)  NOT NULL , 
     gender_id   CHAR (1)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PASSENGER.pass_id IS 'Passenger identifier
Foreign key to another passenger acting as a guardian (only applicable for minors and named guardian_id)' 
;

COMMENT ON COLUMN PASSENGER.pass_fname IS 'Passenger''s first name' 
;

COMMENT ON COLUMN PASSENGER.pass_lname IS 'Passenger''s last name' 
;

COMMENT ON COLUMN PASSENGER.pass_dob IS 'Passenger''s date of birth' 
;

COMMENT ON COLUMN PASSENGER.pass_phone IS 'Phone number of passenger' 
;

COMMENT ON COLUMN PASSENGER.guardian_id IS 'Passenger identifier
Foreign key to another passenger acting as a guardian (only applicable for minors and named guardian_id)' 
;

COMMENT ON COLUMN PASSENGER.add_id IS 'Address identifier (surrogate key)' 
;

COMMENT ON COLUMN PASSENGER.gender_id IS 'Gender identifier (F-Female, M-Male, N-Non-Binary, T-Transgender, O-Others)' 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT PASSENGER_PK PRIMARY KEY ( pass_id ) ;

CREATE TABLE PORT 
    ( 
     port_code       CHAR (5)  NOT NULL , 
     port_name       VARCHAR2 (100)  NOT NULL , 
     port_latitude   NUMBER (2,6)  NOT NULL , 
     port_longtitude NUMBER (3,6)  NOT NULL , 
     country_code    CHAR (3)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PORT.port_code IS 'Port code identifier' 
;

COMMENT ON COLUMN PORT.port_name IS 'Name of port' 
;

COMMENT ON COLUMN PORT.port_latitude IS 'Latitude of port' 
;

COMMENT ON COLUMN PORT.port_longtitude IS 'Longitude of port' 
;

COMMENT ON COLUMN PORT.country_code IS 'Country code act as identifier' 
;

ALTER TABLE PORT 
    ADD CONSTRAINT PORT_PK PRIMARY KEY ( port_code ) ;

CREATE TABLE SHIP 
    ( 
     ship_code               NUMBER (7)  NOT NULL , 
     ship_name               VARCHAR2 (50)  NOT NULL , 
     ship_date_commisioned   DATE  NOT NULL , 
     ship_tonnage            NUMBER (7)  NOT NULL , 
     ship_max_guest          NUMBER (7)  NOT NULL , 
     ship_registered_country VARCHAR2 (50)  NOT NULL , 
     oper_id                 NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN SHIP.ship_code IS 'Ship identifier' 
;

COMMENT ON COLUMN SHIP.ship_name IS 'Name of ship' 
;

COMMENT ON COLUMN SHIP.ship_date_commisioned IS 'Date the ship was commissioned' 
;

COMMENT ON COLUMN SHIP.ship_tonnage IS 'Ship''s tonnage' 
;

COMMENT ON COLUMN SHIP.ship_max_guest IS 'Maximum guest of the ship' 
;

COMMENT ON COLUMN SHIP.ship_registered_country IS 'Ship''s registered country' 
;

COMMENT ON COLUMN SHIP.oper_id IS 'Operator ID identifier' 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT SHIP_PK PRIMARY KEY ( ship_code ) ;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT add_pass_fk FOREIGN KEY 
    ( 
     add_id
    ) 
    REFERENCES ADDRESS 
    ( 
     add_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT cabin_manifest_fk FOREIGN KEY 
    ( 
     cabin_no,
     ship_code
    ) 
    REFERENCES CABIN 
    ( 
     cabin_no,
     ship_code
    ) 
;

ALTER TABLE PORT 
    ADD CONSTRAINT country_port_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT cruise_itinerary_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT cruise_manifest_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT gender_passenger_fk FOREIGN KEY 
    ( 
     gender_id
    ) 
    REFERENCES GENDER 
    ( 
     gender_id
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT oper_ship_fk FOREIGN KEY 
    ( 
     oper_id
    ) 
    REFERENCES OPERATOR 
    ( 
     oper_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT pass_manifest_fk FOREIGN KEY 
    ( 
     pass_id
    ) 
    REFERENCES PASSENGER 
    ( 
     pass_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT passguardian_passminor_fk FOREIGN KEY 
    ( 
     guardian_id
    ) 
    REFERENCES PASSENGER 
    ( 
     pass_id
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT port_itinerary_fk FOREIGN KEY 
    ( 
     port_code
    ) 
    REFERENCES PORT 
    ( 
     port_code
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT ship_cabin_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT ship_cruise_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

set echo OFF
spool OFF